---
- name: Ensure Docker configuration directory exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Change mirror registry for docker
  template:
    src: docker_daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: Restart service docker and daemon-reload to pick up config changes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

