all:
  children:
    web:
      hosts:
        repo-server:
          ansible_host: 185.204.171.165
          ansible_user: ubuntu
        replicate-repo-server:
          ansible_host: 185.204.169.25
          ansible_user: ubuntu