server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: audit_log
        __path__: /var/log/*/*.log
    - targets:
        - localhost
      labels:
        job: varlog
        __path__: /var/log/*.log
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # filters:
          # - name: label
            # values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_logging']
        regex: '(.*)'
        action: keep
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'