---

- name: replace apt mirror on ubuntu
  become: true
  template:
    src: templates/sources.list.ubuntu.j2
    dest: /etc/apt/sources.list
    backup: yes
  register: replace_ubuntu_apt_config
  when: "'iran' in (labels | default([]))"

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install basic tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Fix /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"