IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "nginx"

    config.vm.network "private_network", ip: "192.168.56.10"
    
    config.vm.provider "virtualbox" do |vb|
        vb.name = "nginx"
        # http port
        # config.vm.network "forwarded_port", guest: 80, host: 8080
        config.vm.network "forwarded_port", guest: 80, host: 8082
        # https port
        # config.vm.network "forwarded_port", guest: 443, host: 443
        vb.memory = "1024"
        vb.cpus = 2
    end
    
    config.vm.provision :shell, path: "bootstrap.sh"
end