all:
  children:
    elk-stack:
      hosts:
        elk-server:
          ansible_host: 185.204.170.110
          ansible_user: ubuntu
    test:
      hosts:
        test-server-1:
          ansible_host: 194.5.207.166
          ansible_user: ubuntu
        test-server-2:
          ansible_host: 194.5.207.229
          ansible_user: ubuntu