- name: Set services list
  set_fact:
    compose_services:
      - traefik
      - minio

- name: Deploy services in loop
  include_tasks: deploy_services.yaml
  loop: "{{ compose_services }}"
  loop_control:
    loop_var: service

- name: configure minio
  include_tasks: minio.yaml
  when: "'minio' in compose_services and inventory_hostname == 'tools-server'"
  tags: minio