version: '3.8'

volumes:
  elasticsearch_data:
    name: elasticsearch_data

networks:
  public_net:
    external: true
    name: public_net
  private_net:
    external: true
    name: private_net

services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    restart: ${RESTART_POLICY}
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      node.name: elasticsearch
      network.host: 0.0.0.0
      http.port: 9200
      cluster.name: docker-cluster
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
      xpack.security.authc.api_key.enabled: "true"
      xpack.license.self_generated.type: basic
      xpack.security.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/health-check.sh:/usr/share/elasticsearch/health-check.sh
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - public_net
      - private_net
    healthcheck:
      test: [ "CMD", "sh",  "/usr/share/elasticsearch/health-check.sh" ]
      interval: 30s
      timeout: 3s
    labels:
      - traefik.enable=true
      - traefik.docker.network=public_net
      - traefik.http.routers.elasticsearch.entrypoints=http
      - traefik.http.routers.elasticsearch.rule=Host(`${ELASTICSEARCH_SUB_DOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.elasticsearch.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.elasticsearch-secure.entrypoints=https
      - traefik.http.routers.elasticsearch-secure.rule=Host(`${ELASTICSEARCH_SUB_DOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.elasticsearch-secure.tls=true
      - traefik.http.routers.elasticsearch-secure.tls.options=default
      - traefik.http.routers.elasticsearch-secure.tls.certresolver=default
      - traefik.http.services.elasticsearch.loadbalancer.server.port=9200

  logstash:
    image: logstash:${ELK_VERSION}
    container_name: logstash
    restart: ${RESTART_POLICY}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_HOSTNAME: ${ELASTICSEARCH_HOSTNAME}
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}

      # ELASTICSEARCH_HOSTNAME: ${ELASTICSEARCH_HOSTNAME}
      # ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      # ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      
    networks:
      - private_net
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana
    restart: ${RESTART_POLICY}
    environment:
      - "SERVERNAME=kibana"
      - "ELASTICSEARCH_HOSTNAME=${ELASTICSEARCH_HOSTNAME}"
      - "ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}"
      - "ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}"
      - "KIBANA_PUBLIC_URL=${KIBANA_PUBLIC_URL}"
      - "MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true"
      - "XPACK_FLEET_ENABLED=true"
      - "XPACK_FLEET_AGENTS_ENABLED=true"
      - "XPACK_FLEET_AGENTS_ELASTICSEARCH_HOST=${ELASTICSEARCH_HOSTNAME}"
      - "XPACK_FLEET_AGENTS_FLEET_SERVER_HOSTS=[\"http://fleet:8220\"]"
      - "XPACK_FLEET_AGENTS_TLSCHECKDISABLED=true"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
      test: "curl -f http://localhost:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    networks:
      - public_net
      - private_net
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public_net"
      - "traefik.http.routers.kibana.entrypoints=http"
      - "traefik.http.routers.kibana.rule=Host(`${KIBANA_SUB_DOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.kibana.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.kibana-secure.entrypoints=https"
      - "traefik.http.routers.kibana-secure.rule=Host(`${KIBANA_SUB_DOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.kibana-secure.tls=true"
      - "traefik.http.routers.kibana-secure.tls.options=default"
      - "traefik.http.routers.kibana-secure.tls.certresolver=default"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

  fleet:
    image: elastic/elastic-agent:${ELK_VERSION}
    restart: ${RESTART_POLICY}
    container_name: fleet
    hostname: "${FLEET_SUB_DOMAIN}.${DOMAIN_NAME}"
    environment:
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOSTNAME}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      FLEET_SERVER_ENABLE: true
      FLEET_SERVER_ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOSTNAME}
      FLEET_SERVER_INSECURE_HTTP: true
      KIBANA_FLEET_SETUP: true
      KIBANA_FLEET_HOST: ${KIBANA_HOSTNAME}
      FLEET_SERVER_HOST: 0.0.0.0
      FLEET_SERVER_PORT: 8220
    networks:
      - private_net
      - public_net
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://127.0.0.1:8220/api/status | grep HEALTHY 2>&1 >/dev/null"
      retries: 12
      interval: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public_net"
      - "traefik.http.routers.fleet.entrypoints=http"
      - "traefik.http.routers.fleet.rule=Host(`${FLEET_SUB_DOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.fleet.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.fleet-secure.entrypoints=https"
      - "traefik.http.routers.fleet-secure.rule=Host(`${FLEET_SUB_DOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.fleet-secure.tls=true"
      - "traefik.http.routers.fleet-secure.tls.options=default"
      - "traefik.http.routers.fleet-secure.tls.certresolver=default"
      - "traefik.http.services.fleet.loadbalancer.server.port=8220"
