- name: Configure iptables and make rules persistent
  hosts: all
  become: true
  tasks:
    - name: Install iptables and iptables-persistent packages
      apt:
        name:
          - iptables
          - iptables-persistent
        state: present

    - name: Allow SSH from specific IP
      iptables:
        table: filter
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.56.1
        jump: ACCEPT

    - name: Drop all other incoming traffic
      iptables:
        table: filter
        chain: INPUT
        jump: DROP