IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "ip-table"

    config.vm.network "private_network", type: "dhcp"
    
    config.vm.provider "virtualbox" do |vb|
        vb.name = "ip-table"
        vb.memory = "1024"
        vb.cpus = 2
    end
    
    config.vm.provision :shell, path: "bootstrap.sh"
end