networks:
  web_net:
    name: web_net
    external: true

volumes:
  traefik-acme:
    name: traefik-acme

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    command:
      - --log.filepath=/log-file.log
      - --log.format=json
      - --api=true
      - --api.insecure=true
      - --ping=true
      - --accesslog=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web_net
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.default.acme.email=cert@mvajhi.ir
      - --certificatesresolvers.default.acme.storage=/acme/acme.json
      - --certificatesresolvers.default.acme.tlschallenge=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.mvajhi.ir`)
      - traefik.http.routers.traefik-sec.entrypoints=https
      - traefik.http.routers.traefik-sec.rule=Host(`traefik.mvajhi.ir`)
      - traefik.http.routers.traefik-sec.tls=true
      - traefik.http.routers.traefik-sec.tls.certresolver=default

      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=redirect-to-https

      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik_metrics.entrypoints=http
      - traefik.http.middlewares.test-auth.basicauth.users=mahdi:{SHA}cRDtpNCeBiql5KOQsKVyrA0sAiA=
      - traefik.http.routers.traefik-sec.middlewares=test-auth
    networks:
      - web_net