networks:
  web_net:
    name: web_net
    external: true

volumes:
  traefik-acme:
    name: traefik-acme

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    command:
      - --log.level=ERROR
      - --log.filepath=/log-file.log
      - --log.format=json
      - --api.insecure=true
      - --ping=true
      - --accesslog=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web_net
      - --entrypoints.http.address=:80
      - --metrics.prometheus=true
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`web.t.localhost`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik_metrics.entrypoints=http
    networks:
      - web_net