---
- name: create public_net network
  docker_network:
    name: public_net

- name: create private_net network
  docker_network:
    name: private_net

- name: pull docker images
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    source: pull
  loop: "{{ docker_images }}"

- name: adding existing user "{{ ansible_user }}" to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
