apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    isDefault: false
    jsonData:
      timeInterval: 15s
      httpHeaderName1: Connection
      httpHeaderName2: Upgrade
    secureJsonData:
      httpHeaderValue1: Upgrade
      httpHeaderValue2: websocket

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    isDefault: false
    jsonData:
      implementation: prometheus