IMAGE = "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE
    
    config.vm.hostname = "hello-world"
    
    config.vm.provider "virtualbox" do |vb|
        vb.name = "hello-world"
        vb.memory = "1024"
        vb.cpus = 2
    end
    
    config.vm.provision :shell, path: "bootstrap.sh"
end